[metadata]
format.version = "1.1"

[versions]
assertj = "3.25.1"
edc = "0.4.1"
junit-pioneer = "2.2.0"
jupiter = "5.10.1"
rsApi = "3.1.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
edc-api-core = { module = "org.eclipse.edc:api-core", version.ref = "edc" }
edc-boot = { module = "org.eclipse.edc:boot", version.ref = "edc" }
edc-build-plugin = { module = "org.eclipse.edc.edc-build:org.eclipse.edc.edc-build.gradle.plugin", version.ref = "edc" }
edc-configuration-filesystem = { module = "org.eclipse.edc:configuration-filesystem", version.ref = "edc" }
edc-connector-core = { module = "org.eclipse.edc:connector-core", version.ref = "edc" }
edc-http = { module = "org.eclipse.edc:http", version.ref = "edc" }
jakarta-rsApi = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "rsApi" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter" }
junit-pioneer = { module = "org.junit-pioneer:junit-pioneer", version.ref = "junit-pioneer" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
